// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login.sql

package database

import (
	"context"
)

const checkDBHash = `-- name: CheckDBHash :one
SELECT hashed_password FROM users
WHERE email = $1
`

func (q *Queries) CheckDBHash(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, checkDBHash, email)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}
